version: '3'

services:
  api:
    container_name: api
    env_file: .env.dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - database
    networks:
      - main

  database:
    container_name: database
    env_file: .env.dev
    image: mongo:latest
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

networks:
  main:

volumes:
  mongo_data:
