version: '3'

services:
  vavatips-api-test:
    container_name: vavatips-api-test
    env_file: .env.test
    deploy:
      resources:
        limits:
          memory: 1G
    image: node:18-alpine
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - vavatips-db-test
    networks:
      - test
      - main

  vavatips-db-test:
    container_name: vavatips-db-test
    env_file: .env.test
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_test:/data/db

networks:
  test:
  main:

volumes:
  mongo_data_test:
