version: '3'

services:
  api-test:
    container_name: api-test
    env_file: .env.test
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - valorant-tips-database-test
    networks:
      - test

  valorant-tips-database-test:
    container_name: valorant-tips-database-test
    env_file: .env.test
    image: mongo:latest
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - test

networks:
  test:

volumes:
  mongo_data:
