services:
  vavatips-api:
    container_name: vavatips-api
    env_file: .env.dev
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - vavatips-api-mongodb
    networks:
      - main

  vavatips-api-mongodb:
    container_name: vavatips-api-mongodb
    env_file: .env.dev
    image: mongo:latest
    build:
      context: ./
      dockerfile: ./database/Dockerfile.dev
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - main

networks:
  main:

volumes:
  mongo_data:
