@bearerToken =
@baseUrl = http://localhost:3333
@tokenCode = 3a1483a2-b7fb-412b-803e-3b3e0a3b0283

### @name createUser

POST {{baseUrl}}/users HTTP/1.1
content-type: application/json
accept-language: pt-br

{
  "username":"dev",
  "password":"dev",
  "code": "{{tokenCode}}"
}

### @name uploadFile

### @name getMe

GET {{baseUrl}}/users/me HTTP/1.1
Authorization: {{bearerToken}}


### @name updateUser

PATCH  {{baseUrl}}/users HTTP/1.1
Authorization: {{bearerToken}}
content-type: application/json
accept-language: pt-br

{
  "username":"ademirss2",
  "password":"ademirss2",
  "image":"https://image-ademir.com/image.jpg"
}


### @name deleteThis

DELETE  {{baseUrl}}/users HTTP/1.1
Authorization: {{bearerToken}}

